name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Cambia a "ubuntu-24.04" si ya quieres adaptarte al cambio.
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.11, 3.12]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: mysite.settings # Ajusta según tu configuración.
      continue-on-error: false # Cambiar a `true` si deseas continuar pese a fallos.

    - name: Upload Test Results
      if: failure()
      run: |
        echo "Tests failed in Python ${{ matrix.python-version }}. Check logs."
